### ISSUE TITLE
ABOUT PAGE- FOR PRANAV

### ISSUE THREAD

**Issue by 201BusProject** [201BusProject/201busproject#10]
1. all links working on herokuapp
2. footer looks good but I don't see your name Pranav! Should we make the footer bigger then?
3. Noticed the font change 
4. Is the text lato though? wait it looks like Helvetica. 
5. IMP- Need to incorporate the IFA logo. Sending it to you via gmail.
6. Could there be more spacing between the heading and the text?
7. The text should align with the about page icon on the left. 
8. Bus image- Is there a way to get the full bus? no na?

**Comment by 201BusProject** [comment]
2. Oh right I was trying to reduce the size of the footer to accommodate the entire image but that wasn't helping. I will fix that.
3. Yes the font used everywhere (I think) is helvetica.
5. Where would you like to incorporate the logo? top right?
7. Aligned as in? on the same level?
8. I can try reducing the size of the image. Some or the other part of the image was getting cut earlier.

**Comment by pranman11** [comment]
Have included following changes in latest commit:

1. Removed the background image (testing) 
2. Blue color for buttons changed with color provided 
3. Reversing hover color of button "Catch a 201"
4. Remove bold text from about page 
5. Added names at the bottom of the page, instead of footer
6. IFA logo added according to the guidelines provided (To be verified)
7. change about page icon to home icon instead of envelope
8. Remove the footer on sound page
9. Toast text changed to "Pick another Bus Stop as destination!" 
10. Zoomed out initial map to 12.3 instead of 12.5 earlier
11. Images slide automatically until last image
