### ISSUE TITLE
MAP 

### ISSUE THREAD

**Issue by 201BusProject** [201BusProject/201busproject#9]
1.The routes look quite thick ?
2.  Some are not accurate. Need to change

**Comment by Vrroom** [comment]
I think I can automatically make them snap on to the nearest road. Since you guys have jotted down the points, I can use some service to get the points on the road in between the jotted points. 

Thickness is easy to solve. Perhaps, me or @pranman11 should show you alternative thickness'. Maybe we can have thickness as a function of the zoom. If you zoom in more, the lines are thinner, as you zoom out, they become slightly thick. Actually as I'm writing this, I don't know what purpose it'll serve.

**Comment by 201BusProject** [comment]
Ya no need for the thickness to vary with zoom.

**Comment by pranman11** [comment]
@Vrroom where have you used the coordinates from? Is it from the files that were created for each bus route? Otherwise we can use https://geojson.io for new coordinates.

**Comment by Vrroom** [comment]
I took the bus routes that you guys made. For each pair of adjacent bus stops, I derived routes from those by finding the index in the route at which those bus stops appear (based on euclidean distance of coordinates).

**Comment by pranman11** [comment]
Oh then I wonder why the routes are not accurate? I remember making sure that the route of a particular bus has all the bus stops of that journey.

**Comment by Vrroom** [comment]
No that is fine. It is just that they don't follow the roads if you zoom carefully.
